export const PRODUCT_FETCH = 'PRODUCT_FETCH';
export const PRODUCT_FETCH_DETAIL = 'PRODUCT_FETCH_DETAIL';
export const PRODUCT_RECEIVER = 'PRODUCT_RECEIVER';
export const PRODUCT_SEARCH_CLEAR = 'PRODUCT_SEARCH_CLEAR';
export const PRODUCT_RECEIVER_MORE = 'PRODUCT_RECEIVER_MORE';
export const PRODUCT_RECEIVER_SEARCH = 'PRODUCT_RECEIVER_SEARCH';
export const PRODUCT_RECEIVER_DETAIL = 'PRODUCT_RECEIVER_DETAIL';
//token
export const TOKEN_FETCH = 'TOKEN_FETCH';
export const TOKEN_RECEIVER = 'TOKEN_RECEIVER';

export const CLASSIFY_FETCH = 'CLASSIFY_FETCH';
export const CLASSIFY_RECEIVER = 'CLASSIFY_RECEIVER';
export const CLASSIFY_RECEIVER_CHILD = 'CLASSIFY_RECEIVER_CHILD';

export const DISTRIBUTE_FETCH = 'DISTRIBUTE_FETCH';
export const DISTRIBUTE_RECEIVER = 'DISTRIBUTE_RECEIVER';
export const SHOP_FETCH = 'SHOP_FETCH';
export const SHOP_RECEIVER = 'SHOP_RECEIVER';

export const ADDRESS_FETCH = 'ADDRESS_FETCH';
export const ADDRESS_RECEIVER = 'ADDRESS_RECEIVER';
export const ADDRESS_UPDATE = 'ADDRESS_UPDATE';
export const ADDRESS_ADD = 'ADDRESS_ADD';